apiVersion: v1
kind: Pod
metadata:
  name: nodejspod
  labels:
    app: nodejs
spec:
  containers:
    - name: nodejscontainer
      image: sravsdocker26/nodejs:1
      ports:
      - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsdeploy
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      name: nodejspod
      labels:
        app: nodejs
    spec:
      containers:
      - name:nodejs 
        image: sravsdocker26/nodejs:1
        ports:
        - containerPort: 3000
 ---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: ingress_resource
spec:
  rules:
  - host: nginx.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nodejs-service
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:  
  name: nodejs_service
spec:
  selector:    
    app: nodejs
  type: NodePort
  ports:  
    port: 80
    targetPort: 3000
