apiVersion: v1
kind: Pod
metadata:
  name: nodejspod
  labels:
    app: nodejs
spec:
  containers:
    - name: nodejscontainer
      image: sravsdocker26/nodejs:1
      ports:
      - containerPort: 3000
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsdeploy
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      name: nodejspod
      labels:
        app: nodejs
    spec:
      containers:
      - name:nodejs 
        image: sravsdocker26/nodejs:1
        ports:
        - containerPort: 3000
 ---
 apiVersion: v1
kind: Service
metadata:  
  name: nodeport
spec:
  selector:    
    app: nodejs
  type: NodePort
  ports:  
    port: 80
    targetPort: 3000
